Feature/tao 9045/delivery assembly package
oat-sa/extension-tao-sync-server pull request #6
Opened 2020-01-10 12:09 UTC by yuryfilippovich

2020-01-15 10:16 UTC, ks16 requested changes
Requires changes in implementation as was discussed with @yuryfilippovich

2020-01-16 09:06 UTC, ks16 requested changes
As we discussed, could you please register events listeners for delivery updated/deleted events and remove exported assembly files on these events.

2020-01-16 09:06 UTC, ks16 commented on export/service/ExportDeliveryAssembly.php
> +    private function getAssembler()
Can we move $encryptionService creation to `getAssemblyExporter` method and remove this one? I cannot see a point of having this method just for that.

2020-01-16 09:06 UTC, ks16 commented on export/service/ExportDeliveryAssembly.php
> +    public function createCompiledDeliveryPackage(array $deliveryUris)
I think it would be better to call this method something like `exportDeliveryAssemblies`, because that closer to what it does.

2020-01-16 09:06 UTC, ks16 commented on export/service/ExportDeliveryAssembly.php
> +    const OUTPUT_TEST_FORMAT = CompiledTestConverterFactory::COMPILED_TEST_FORMAT_XML;
I think we can use `CompiledTestConverterFactory::COMPILED_TEST_FORMAT_XML` constant directly.

2020-01-16 09:06 UTC, ks16 commented on export/service/ExportDeliveryAssembly.php
> +                if (!$assemblerFile->write(file_get_contents($exportedAssemblyPath))) {
We can use this helper class to work with files - https://github.com/oat-sa/tao-core/blob/master/helpers/class.File.php. It has methods to sanitize filename, move file, etc.

2020-01-16 12:41 UTC, yuryfilippovich commented on export/service/ExportDeliveryAssembly.php
> +    private function getAssembler()
getAssemblyExporter method removed

2020-01-16 12:42 UTC, yuryfilippovich commented on export/service/ExportDeliveryAssembly.php
> +    private function getAssembler()
getAssemblyExporter method removed

2020-01-16 12:42 UTC, yuryfilippovich commented on export/service/ExportDeliveryAssembly.php
> +    public function createCompiledDeliveryPackage(array $deliveryUris)
changed

2020-01-16 12:42 UTC, yuryfilippovich commented on export/service/ExportDeliveryAssembly.php
> +    const OUTPUT_TEST_FORMAT = CompiledTestConverterFactory::COMPILED_TEST_FORMAT_XML;
fixed

2020-01-16 14:22 UTC, ks16 approved these changes
Approved

2020-01-16 14:22 UTC, merged